name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  batch: true
  branches:
    include:
    - master
    - rel/*
pr:
- '*'
resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   thnetii
jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    independantRuntime:
      arguments:        '-p:NoNetFramework=false'
      pool:
        vmImage:        windows-latest
    windowsRuntime:     ${{ variables.null }}
    linuxRuntime:       ${{ variables.null }}
    macRuntime:         ${{ variables.null }}

